budget: 30
items {
    name: "dip"
    amount: 1
    expect_cost: 6.50
    favorites: "hummus"
    favorites: "garlic"
}
items {
    name: "hot sauce"
    amount: 3
    variety: true
    expect_unit_cost: 6.50
    favorites: "yuzu"
    favorites: "kiss"
    favorites: "fire"
    favorites: "bee"
    favorites: "sunshine"
}
